# Generated by Django 5.2.8 on 2025-11-19 11:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=50, unique=True, verbose_name='Buyurtma Raqami')),
                ('pdf_file', models.FileField(upload_to='order_pdfs/', verbose_name='PDF Fayl')),
                ('customer_name', models.CharField(max_length=100, verbose_name='Xaridor Nomi')),
                ('status', models.CharField(choices=[('KIRITILDI', '1. Kiritildi (Admin)'), ('TASDIQLANDI', '2. Tasdiqlandi (Menejer)'), ('ISHDA', '3. Ishlab Chiqarishda (Boshliq)'), ('TAYYOR', '4. Tayyor (Boshliq)')], default='KIRITILDI', max_length=20, verbose_name='Hozirgi Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
