# Generated by Django 5.2.8 on 2025-11-19 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_panel_kvadrat_alter_order_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Umumiy Narx (Summa)'),
        ),
    ]
