# Generated by Django 5.2.8 on 2025-11-19 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('KIRITILDI', '1. Kiritildi (Admin)'), ('TASDIQLANDI', '2. Tasdiqlandi (Menejer)'), ('RAD_ETILDI', '2. Rad Etildi (Menejer)'), ('ISHDA', '3. Ishlab Chiqarishda (Boshliq)'), ('TAYYOR', '4. Tayyor (Boshliq)'), ('BAJARILDI', '5. Bajarildi (Menejer/Yakuniy)')], default='KIRITILDI', max_length=20, verbose_name='Hozirgi Status'),
        ),
    ]
