# Generated by Django 5.2.8 on 2025-11-20 05:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_order_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('PANEL', 'Panel Ustasi'), ('LIST', 'List Ustasi'), ('ESHIK', 'Eshik Ustasi'), ('UGOL', 'Ugol Ustasi')], max_length=50, verbose_name='Usta Roli')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='worker_profile', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Usta',
                'verbose_name_plural': 'Ustalar',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='assigned_workers',
            field=models.ManyToManyField(blank=True, related_name='assigned_orders', to='orders.worker', verbose_name='Belgilangan Ustalar'),
        ),
    ]
