# Generated by Django 5.2.8 on 2025-11-22 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_worker_order_assigned_workers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'verbose_name': 'Buyurtma', 'verbose_name_plural': 'Buyurtmalar'},
        ),
        migrations.AddField(
            model_name='order',
            name='deadline',
            field=models.DateTimeField(blank=True, help_text="Usta bu muddatgacha ishni tugatishi kerak. Ushbu sana o'tgach, Admin/Menejerlarga ogohlantirish yuboriladi.", null=True, verbose_name='Belgilangan Muddat (Deadline)'),
        ),
        migrations.AddField(
            model_name='order',
            name='worker_finished_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Usta Tugatgan Vaqti'),
        ),
        migrations.AddField(
            model_name='order',
            name='worker_started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Usta Boshlagan Vaqti'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('KIRITILDI', '1. Kiritildi (Admin)'), ('TASDIQLANDI', '2. Tasdiqlandi (Menejer)'), ('RAD_ETILDI', '2. Rad Etildi (Menejer)'), ('USTA_QABUL_QILDI', '3. Usta Qabul Qildi (Tovar Olingan)'), ('USTA_BOSHLA', '4. Usta Boshladi (Ishga Kirishdi)'), ('ISHDA', '5. Ishlab Chiqarishda (Boshliq)'), ('USTA_TUGATDI', '6. Usta Yakunladi (Ish Tugatildi)'), ('TAYYOR', '7. Tayyor (Sifat Nazorati)'), ('BAJARILDI', '8. Bajarildi (Yakuniy)')], default='KIRITILDI', max_length=30, verbose_name='Hozirgi Status'),
        ),
    ]
