# Generated by Django 5.2.8 on 2025-11-23 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_order_options_order_deadline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='deadline_breach_alert_sent',
            field=models.BooleanField(default=False, verbose_name='Muddat Buzilishi Ogohlantirilgan'),
        ),
        migrations.AlterField(
            model_name='order',
            name='deadline',
            field=models.DateTimeField(blank=True, help_text='Usta bu muddatgacha ishni tugatishi kerak.', null=True, verbose_name='Belgilangan Muddat (Deadline)'),
        ),
    ]
