# Generated by Django 5.2.8 on 2025-11-23 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_order_deadline_breach_alert_sent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='finish_image',
            field=models.ImageField(blank=True, null=True, upload_to='order_photos/finish/', verbose_name='Ish Yakunlash Rasmi'),
        ),
        migrations.AddField(
            model_name='order',
            name='start_image',
            field=models.ImageField(blank=True, null=True, upload_to='order_photos/start/', verbose_name='Ish Boshlash Rasmi'),
        ),
        migrations.AlterField(
            model_name='order',
            name='deadline',
            field=models.DateTimeField(blank=True, help_text="Usta bu muddatgacha ishni tugatishi kerak. Ushbu sana o'tgach, Admin/Menejerlarga ogohlantirish yuboriladi.", null=True, verbose_name='Belgilangan Muddat (Deadline)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='deadline_breach_alert_sent',
            field=models.BooleanField(default=False, verbose_name='Muddat Buzilganligi Ogohlantirish Yuborildi'),
        ),
    ]
