# Generated by Django 5.2.8 on 2025-11-23 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_order_finish_image_order_start_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name="Izoh/Qo'shimcha Ma'lumot"),
        ),
        migrations.AddField(
            model_name='order',
            name='product_name',
            field=models.CharField(default=1989, help_text='Buyurtma berilgan mahsulot yoki kategoriya nomi', max_length=255, verbose_name='Mahsulot Nomi'),
            preserve_default=False,
        ),
    ]
