# Generated by Django 5.2.8 on 2025-11-24 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_order_comment_order_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='finish_image_uploaded_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Tugatish Rasmi Yuklangan Vaqt'),
        ),
        migrations.AddField(
            model_name='order',
            name='start_image_uploaded_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Boshlash Rasmi Yuklangan Vaqt'),
        ),
        migrations.AlterField(
            model_name='order',
            name='deadline',
            field=models.DateTimeField(blank=True, help_text='Usta bu muddatgacha ishni tugatishi kerak.', null=True, verbose_name='Belgilangan Muddat (Deadline)'),
        ),
    ]
