# Generated by Django 5.2.8 on 2025-11-24 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_order_finish_image_uploaded_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='worker_comment',
            field=models.TextField(blank=True, null=True, verbose_name='Usta Izohlari'),
        ),
    ]
