# Generated by Django 5.2.8 on 2025-11-25 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_order_worker_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('KIRITILDI', '1. Kiritildi (Admin)'), ('TASDIQLANDI', '2. Tasdiqlandi (Menejer)'), ('RAD_ETILDI', '2. Rad Etildi (Menejer)'), ('USTA_QABUL_QILDI', '3. Usta Qabul Qildi (Tovar Olingan)'), ('USTA_BOSHLA', '4. Usta Boshladi (Ishga Kirishdi)'), ('ISHDA', '5. Ishlab Chiqarishda (Menejer)'), ('USTA_TUGATDI', '6. Usta Yakunladi (Ish Tugatildi)'), ('TAYYOR', '7. Tayyor (Sifat Nazorati)'), ('BAJARILDI', '8. Bajarildi (Yakuniy)')], default='KIRITILDI', max_length=30, verbose_name='Hozirgi Status'),
        ),
    ]
