# Generated by Django 5.2.8 on 2025-11-25 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delayed_assignment_alert_sent',
            field=models.BooleanField(default=False, verbose_name='Ishga Berish Kechikkanligi Ogohlantirish Yuborildi'),
        ),
    ]
