# Generated by Django 5.2.8 on 2025-11-25 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_order_delayed_assignment_alert_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='telegram_notified_overdue',
            field=models.BooleanField(default=False, verbose_name='Telegramga muddat haqida xabar berilgan'),
        ),
    ]
